{
 "title": "clip-as-service",
 "description": "The datashboard for CLIP-as-service",
 "tags": [
  "clip",
  "jina"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Endpoint",
    "query": {
     "query": "label_values(jina_document_processed_created,executor_endpoint)\n"
    }
   },
   {
    "name": "Executor",
    "query": {
     "query": "label_values(jina_document_processed_created,runtime_name)\n"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "life cycle of a request",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jina_receiving_request_seconds_sum / jina_receiving_request_seconds_count",
     "legendFormat": "receiving-{{job}}"
    },
    {
     "expr": "jina_sending_request_seconds_sum / jina_sending_request_seconds_count",
     "legendFormat": "sending-{{job}}"
    },
    {
     "expr": "jina_preprocess_texts_seconds_sum / jina_preprocess_texts_seconds_count",
     "legendFormat": "preproc text"
    },
    {
     "expr": "jina_encode_texts_seconds_sum / jina_encode_texts_seconds_count",
     "legendFormat": "encode text"
    },
    {
     "expr": "jina_process_request_seconds_sum / jina_process_request_seconds_count",
     "legendFormat": "processing-encode"
    },
    {
     "expr": "jina_preprocess_images_seconds_sum / jina_preprocess_images_seconds_count",
     "legendFormat": "preproc image"
    },
    {
     "expr": "jina_encode_images_seconds_sum / jina_encode_images_seconds_count",
     "legendFormat": "encode image"
    }
   ]
  },
  {
   "title": "Number of Request processed ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jina_receiving_request_seconds_count{runtime_name=~\"gateway.*\"}"
    }
   ]
  },
  {
   "title": "jina_receiving_request_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jina_receiving_request_seconds_sum / jina_receiving_request_seconds_count",
     "legendFormat": "{{runtime_name}}"
    }
   ]
  },
  { "title": "$Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "Executor" },
  {
   "title": "Number of Documents processed per endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jina_document_processed_total{runtime_name=\"$Executor\"}",
     "legendFormat": "{{executor_endpoint}}"
    }
   ]
  },
  {
   "title": "Number of requests per endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jina_process_request_seconds_count{runtime_name=\"$Executor\"}",
     "legendFormat": "{{executor_endpoint}}"
    }
   ]
  },
  {
   "title": "Time spend calling the Executor method link the to endpoint",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jina_process_request_seconds_sum{runtime_name=\"$Executor\"} / jina_process_request_seconds_count{runtime_name=\"$Executor\"}",
     "legendFormat": "{{executor_endpoint}}-process"
    }
   ]
  },
  {
   "title": "Time spend calling between receiving and responding ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jina_receiving_request_seconds_sum{runtime_name=\"$Executor\"} / jina_receiving_request_seconds_count{runtime_name=\"$Executor\"}",
     "legendFormat": "{{executor_endpoint}}"
    }
   ]
  }
 ]
}